# Generated by Django 3.1.4 on 2021-01-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoonblog', '0006_coding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='yoonblog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False),
        ),
    ]
